### PR TITLE
Fix typo in README

### PR DESCRIPTION
**Pull request by nikolas**

### CODE REVIEW

**Comment by mjgiarlo** [comment]
Hi, @nikolas! Thanks for the pull request. In order for us to merge this change, we'll need to have a signed Contributor License Agreement on file for you as an individual. You can read more about our CLA processes here:

https://wiki.duraspace.org/display/hydra/Hydra+Project+Intellectual+Property+Licensing+and+Ownership

The process itself is fairly simple -- you just need to print out the Hydra Project iCLA and sign it and then send it to legal@projecthydra.org. I'm guessing @barmintor may be able to help since he's already been through this process. Let me know if you have any questions about this process, and I'd be happy to help.

**Comment by barmintor** [comment]
Does this mean we still don't have a cCLA on file for CUL?

**Comment by mjgiarlo** [comment]
@barmintor Yes, that is the case. See here: https://wiki.duraspace.org/display/hydra/Hydra+Licensed+Contributors

(But even if there were a cCLA on file for Columbia, we'd still want iCLAs from all individuals ideally.)

**Comment by nikolas** [comment]
@mjgiarlo I don't have a scanner, but even if I did, it seems strange to require me to sign something for this change - pointing out a small typo in the README.

I'd assume this change is "legally insignificant" for copyright purposes. http://www.gnu.org/prep/maintain/maintain.html#Legally-Significant

**Comment by atz** [comment]
Agree with @nikolas on this one.  Let's not get ridiculously legalistic.

**Comment by mjgiarlo** [comment]
I don't disagree but it's not really up to me to judge when to exempt particular PRs from our general IP processes. I'll raise this with the steering group and get back to you.

**Comment by mjgiarlo** [comment]
(Thank you for your patience, and for your contribution!)

**Comment by mjgiarlo** [comment]
The typo has been fixed. Thanks, @nikolas.

**Pull request closed without merging**
