### PR TITLE
Revised text around squashing commits

### PR DESCRIPTION
**Pull request by jcoyne**
Phrased the point to be a guideline rather than a dictate.
This was discussed on the hydra tech call 2015-04-15

### CODE REVIEW

**Comment by atz** [comment]
:+1:

**Comment by ndushay** [comment]
:+1:

**Comment by dchandekstark** [comment]
:+1:

**Comment by awead** [comment]
:+1: Unless anyone else raises objections, I move to merge by end-of-the-day this Friday.

**Comment by mjgiarlo** [comment]
:+1: :clap:

**Comment by hortongn** [comment]
:+1:

**Comment by terrellt** [comment]
:+1:

**Comment by mark-dce** [comment]
:+1:

**Comment by jeremyf** [comment]
:+1:

**Comment by hectorcorrea** [comment]
:+1:

**Pull request merged**
