### PR TITLE
Add hackmasterA so the releasing of a gem can occur

### PR DESCRIPTION
**Pull request by hackmastera**
@awead

### CODE REVIEW

**Comment by awead** [comment]
ping @mjgiarlo. We'd like @hackmastera to release Sufia 6.4.1. If my memory serves, this would allow her to do this.

**Comment by hackmastera** [comment]
(well, 6.5.0, as agreed via https://github.com/projecthydra/sufia/issues/1426)

**Comment by mjgiarlo** [comment]
I'm on it.

**Comment by mjgiarlo** [comment]
Merging and then I'll run it locally.

**Pull request merged**
